version: "3.9"

services:
  lb:
    image: visuzano/rinha-2026:latest
    command: ["/opt/lb"]
    ports:
      - "9999:9999"
    environment:
      - LB_LISTEN=0.0.0.0:9999
      - BACKENDS=api1:8080,api2:8080
      - UPSTREAM_POOL_PER_BACKEND=32
      - UPSTREAM_PRECONNECT_PER_BACKEND=32
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"
    networks:
      - rinha

  api1:
    image: visuzano/rinha-2026:latest
    environment:
      - INDEX_PATH=/opt/index.bin
      - PORT=8080
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - rinha

  api2:
    image: visuzano/rinha-2026:latest
    environment:
      - INDEX_PATH=/opt/index.bin
      - PORT=8080
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
