worker_processes 1;
worker_rlimit_nofile 65536;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    log_format perf escape=json
        '{'
        '"ts":"$time_iso8601",'
        '"request":"$request",'
        '"status":$status,'
        '"request_time":"$request_time",'
        '"upstream_response_time":"$upstream_response_time",'
        '"upstream_status":"$upstream_status",'
        '"upstream_addr":"$upstream_addr",'
        '"bytes_sent":$bytes_sent'
        '}';

    access_log /dev/stdout perf;
    error_log /dev/stderr warn;

    keepalive_timeout 65;
    keepalive_requests 10000;
    tcp_nodelay on;
    tcp_nopush on;

    upstream api {
        keepalive 512;
        server api1:8080;
        server api2:8080;
    }

    server {
        listen 9999;

        location /ready {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
        }

        location /fraud-score {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_read_timeout 30s;
            proxy_send_timeout 30s;
        }
    }
}
